name: Update README

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: false

jobs:
  build:
    name: Build README
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm install
      - name: Update README
        run: |-
          npm run start
          cat README.md
      - name: Commit and push if README has changed
        run: |-
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git diff --quiet || (git add README.md && git commit -m "Update README")
          git push
